language: node_js
node_js:
  - 12.16.2
before_deploy:
- git config --global user.email ${GITHUB_EMAIL}
- git config --global user.name ${GITHUB_USER}
- git remote set-url origin "https://${GITHUB_TOKEN}@github.com/libertymutual/bmo.git" > /dev/null 2>&1
- git checkout master
- npm config set access public
- npm config set registry https://registry.npmjs.org
- npm set //registry.npmjs.org/:_authToken "$NPM_API_TOKEN"
- npm install
deploy:
  provider: script
  script: "echo publishing packages && npm run publish:packages"
  on:
    branch: master
